### ISSUE TITLE
Please update WorldGuard 1.21 Folia version.

### ISSUE THREAD

**Issue by kitovoi111** [Folia-Inquisitors/WorldGuard-Folia#4]
### The Problem

Please update WorldGuard 1.21 Folia version.

### A Solution

Please update WorldGuard 1.21 Folia version.

**Comment by ewof** [comment]
+1

**Comment by KaspianDev** [comment]
#5

**Comment by Yomamaeatstoes** [comment]
@ewof @kitovoi111
